// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3620.GoldenCode2014.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3620.GoldenCode2014.CatapultState;
import org.usfirst.frc3620.GoldenCode2014.Robot;
/**
 *
 */
public class CockAndShootState extends Command {
    long currentTime = System.currentTimeMillis();
    boolean DEBUG = false;
    
    public CockAndShootState() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.catapultSubsystem);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        if (DEBUG) 
            System.out.println("CockAndShootState init");
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        CatapultState currentState = Robot.catapultSubsystem.getCatapultState();
        if (DEBUG) 
          System.out.println ("CockAndShootState sees current state = " + currentState);
        if (currentState == CatapultState.COCKED) {
            Robot.catapultSubsystem.setCatapultState(CatapultState.SHOOTING_DELAY);
        } else if (currentState == CatapultState.COCKING_CAM) {
            //ignoring
        } else if (currentState == CatapultState.COCKING_TIMER) {
            
        } else if (currentState == CatapultState.SHOT) {
            Robot.catapultSubsystem.setCatapultState(CatapultState.COCKING_CAM);
        } else if (currentState == CatapultState.SHOOTING) {
            //ignoring
        } else if (currentState == CatapultState.SHOOTING_DELAY){
            //ignoring
        }
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return true;
    }
    // Called once after isFinished returns true
    protected void end() {
        if (DEBUG)
            System.out.println("CockAndShootState end");
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
